services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:v1.0
    container_name: backed-container
    environment:
      DB_HOST: db
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:v1.0
    container_name: frontend-container
    environment:
      VITE_API_BASE_URL: http://backend:4000
    ports:
      - "3500:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped

volumes:
  db_data: